version: '3.4'

services:
  smart.meters:
    image: engrmnasirilyas716/smartmeters:latest
    # image: ${DOCKER_REGISTRY-}smartmeters
    # build:
    #   context: .
    #   dockerfile: Smart.Meters/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONNECTION_STRING=Server=db;Database=mydb;User=appuser;Password=appuserpass;

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpass
    ports:
      - "3306:3306"
    healthcheck:
      # test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      # test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="password" --silent']
      # timeout: 20s
      # retries: 10
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
